test:
  workers:
    number: 5
  rounds:
    - label: Insert Student
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: src/insertStudent.js
        arguments:
          prefix: 1337

    - label: Insert Department
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: src/insertDepartment.js
        arguments:
          prefix: 1337

    - label: Query a student.
      txDuration: 1000
      rateControl:
          type: fixed-load
          opts:
            transactionLoad: 5
      workload:
        module: src/queryStudent.js
        arguments:
          prefix: 1337
