version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - ./default-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ~/workspaces/ssl-cert/h-1.cloud:/etc/nginx/ssl-cert
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443
